config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :state_scopeable do
    collection do
      get :draft
      get :submitted
      get :approved
      get :fulfilled
      get :archived
    end
  end

  resources :sites, only: [:index] do
    resources :orders, only: [:index], concerns: :state_scopeable
  end

  resources :orders, concerns: :state_scopeable do
    member do
      put :review
      put :submit
      put :approve
      put :fulfill
      put :archive
      put :cancel
    end

    resources :line_items
    resources :comments, only: [:create]
    resources :approvals, only: [:create]
  end

  resources :products
  resources :product_groups
  resources :imports, only: [:new, :create]

  namespace :admin do
    resources :sites
    resources :users
    resources :roles
  end

  authenticated :user, lambda {|u| u.staff?} do
    root to: 'orders#draft', as: :staff_root
  end

  authenticated :user, lambda {|u| u.approver?} do
    root to: 'orders#submitted', as: :approver_root
  end

  authenticated :user, lambda {|u| u.warehouse?} do
    root to: 'orders#approved', as: :warehouse_root
  end

  authenticated :user, lambda {|u| u.finance?} do
    root to: 'orders#fulfilled', as: :finance_root
  end

  root to: 'orders#index'

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  site_id    :integer
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  state      :integer          default("0"), not null
#

class Order < ActiveRecord::Base
  # enum state: { draft: 0, reviewing: 1, submitted: 2, fulfilled: 3, archived: 4, cancelled: 5 }
  belongs_to :site
  belongs_to :user
  
  has_many :line_items, dependent: :destroy
  accepts_nested_attributes_for :line_items, allow_destroy: true
  
  has_many :products, through: :line_items
  has_many :comments
  
  has_many :approvals, dependent: :destroy
  
  validates :user_id, presence: true
  
  include OrderWorkflow
  
  def self.active
    where("state < 2")
  end
  
  def add_product(params)
    current_item = line_items.find_by(product_id: params[:product_id])
    if current_item.present?
      current_item.quantity += (params[:quantity].to_i || 1)
    else
      current_item = line_items.build(params)
    end
    current_item
  end
  
  def editable?
    true
  end
  
  def total_cents
    line_items.map {|li| li.total_cents }.sum
  end
  
  def total
    total_cents.to_f / 100
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrderPermissions
  include OrderQuerying
  before_action :set_order, except: [:index, :draft, :submitted, :fulfilled, :approved, :archived, :new, :create]
  before_action :set_site, only:    [:index, :draft, :submitted, :approved, :fulfilled, :archived]
  before_action :set_groups, only:  [:show, :new, :edit]
  after_action  :authorize_for_orders

  # GET /orders
  # GET /orders.json
  def index
    @orders = orders_for_user.order(created_at: :desc)
  end

  def draft
    @orders = orders_for_user(:draft).order(created_at: :desc)
    render template: 'orders/index'
  end

  def submitted
    @orders = orders_for_user(:submitted).order(created_at: :desc)
    render template: 'orders/index'
  end

  def approved
    @orders = orders_for_user(:approved).order(created_at: :desc)
    render template: 'orders/index'
  end

  def fulfilled
    @orders = orders_for_user(:fulfilled).order(created_at: :desc)
    render template: 'orders/index'
  end

  def archived
    @orders = orders_for_user(:archived).order(created_at: :desc)
    render template: 'orders/index'
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @comments = @order.comments.order(created_at: :desc)
  end

  # GET /orders/new
  def new
    @order = new_order_for current_user
  end

  # GET /orders/1/edit
  def edit
    @order = order_for_user
    unless @order.editable_by?(current_user)
      redirect_to @order, alert: "Sorry you can't edit that."
    end
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new( order_params.merge(user_id: current_user.id, site: current_user.site) )

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        set_groups
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def submit
    handle_state_change("submit!", "submitted.")
  end

  def approve
    handle_state_change("approve!", "approved")
  end

  def fulfill
    handle_state_change("fulfill!", "marked fulfilled.")
  end

  def archive
    handle_state_change("archive!", "archived.")
  end

  def cancel
    handle_state_change("cancel!", "cancelled.")
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def set_groups
    @groups = ProductGroup.order(:group_number).includes(:active_products)
  end

  def set_site
    if params[:site_id]
      @site = Site.by_param(params[:site_id])
    end
  end

  def order_params
    params.require(:order).permit(:site_id, :state, line_items_attributes: [:id, :quantity, :product_id, :_destroy])
  end

  def new_order_for(user)
    Order.new(user: user, site: user.site)
  end

  def handle_state_change(state, msg)
    if @order.send(state)
      redirect_to orders_path, notice: "Order #{msg}."
    else
      redirect_to response.referrer, alert: "Order could not be #{msg}."
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
  
  def next_step_link_for(order)
    link_to order.next_step.name, {controller: 'orders', action: order.next_step.name, id: order.id}, {class: 'btn btn-primary', method: :put}
  end
  
  def order_section_tag(order)
    options = {
      id: 'order-form',
      class: order.line_items.any? ? '' : 'order-empty'
    }
    content_tag :section, options do
      yield if block_given?
    end
  end
  
  def approval_item(role, order)
    approved = order.approvals.where(role: role).any?
    
    li_classes = ['list-group-item']
    li_classes << 'list-group-item-success' if approved
    
    options = {class: li_classes.join(' ')}
    
    icon = approved ? 'glyphicon-ok' : 'glyphicon-remove'
    
    content_tag :li, options do
      content_tag(:span, nil, class: "glyphicon #{icon}") + " #{role.name.titlecase}"
    end
  end
  
  def approval_button(role, order)
    approved = order.approvals.where(role: role).any?
    
    classes = ['btn']
    if approved
      classes << 'btn-success'
    else
      classes << 'btn-default'
    end
    
    icon = approved ? 'glyphicon-ok' : 'glyphicon-time'
    
    options = {
      class: classes.join(' '),
      method: :post
    }
    
    params = {approval: {role_id: role.id}}
    
    if current_user.roles.include? role
      href = order_approvals_path(order, params)
    else
      href = "javascript:;"
    end
    
    link_to href, options do
      content_tag(:span, nil, id: "approve_for_#{role}", class: "glyphicon #{icon}") + " #{role.name.titlecase}"
    end
  end
  
  def new_order_button
    unless current_user.site.nil?
      options = {class: 'btn btn-primary'}
      if current_user.site.orders.draft.any?
        options[:data] = {toggle: 'modal', target: '#new_order_modal'}
        link_to 'New Order', 'javascript:;', options
      else
        options[:id] = 'new_order_button'
        link_to 'New order', new_order_path, options
      end
    end
  end
  
end

app/views/orders/_comments.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      Comments
    </div>
  </div>
  <div class="panel-body">
    <%= render @comments %>
  </div>
  <div class="panel-footer">
    <%= form_for [@order, Comment.new] do |f| %>
      <div class="form-group">
        <%= f.text_area :body, class: 'form-control', placeholder: 'Add a comment' %>
      </div>
      <%= f.submit 'Send', class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/orders/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h5>Order</h5>
    </div>
  </div>
  <div class="panel-body">
    <%= render 'order_form' %>
  </div>
</div>

<hr>

<div id="order-options">
  <%= render @groups %>
</div>

app/views/orders/_header.html.erb
<div class="page-header">
  <h2>Order #<%= @order.id %></h2>
  <p>
    Started <%= @order.created_at.to_s(:short) %> by <%= @order.user.name %>.
    Last edited <%= time_ago_in_words(@order.updated_at) %> ago.
  </p>
</div>

app/views/orders/_order.html.erb
<table class="table table-striped order-table">
  <thead>
    <tr>
      <th>Item ID</th>
      <th>Desc</th>
      <th>Qty</th>
      <th>Unit</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @order.line_items.includes(:product).each do |item| %>
    <tr>
      <td><%= item.product.item_id %></td>
      <td><%= item.description %></td>
      <td><%= item.quantity %></td>
      <td><%= item.measure %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td colspan="2">
        <strong>Total</strong>
      </td>
      <td><%= number_to_currency @order.total %></td>
    </tr>
  </tbody>
</table>

app/views/orders/_order_form.html.erb
<%= order_section_tag @order do %>
  <%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <% unless @order.line_items.any? %>
      <p class="order-empty_state">There are no items in your order yet.</p>
    <% end %>

    <table id="order-items" class="table table-striped">
      <thead>
        <tr>
          <th>Desc</th>
          <th>Qty</th>
          <th>Unit</th>
          <th>Item Total</th>
          <th>Remove</th>
        </tr>
      </thead>
      <tbody>
        <%= f.fields_for :line_items do |item_fields| %>
          <%= render partial: 'line_items/line_item_fields', locals: {f: item_fields} %>
        <% end %>
        <tr class="order-total">
          <td></td>
          <td></td>
          <td><strong>Total</strong></td>
          <td data-bind="order-total"><%= number_to_currency @order.total %></td>
          <td></td>
        </tr>
      </tbody>
    </table>

    <div class="actions">
      <%= f.submit 'Update and Save', class: 'btn btn-primary' %>
    </div>

  <% end %>
  
  <table class="js-template" id="line_item-template">
    <tr class="line_item-fields">
      <td style="display:none">
        <div class="line_item-id"><%= hidden_field_tag 'order[line_items_attributes][-##-][id]' %></div>
        <div class="line_item-product_id"><%= hidden_field_tag 'order[line_items_attributes][-##-][product_id]' %></div>
      </td>
      <td class="line_item-description"></td>
      <td class="line_item-quantity">
        <%= text_field_tag 'order[line_items_attributes][-##-][quantity]', 1, size: 2 %>
      </td>
      <td class="line_item-measure"></td>
      <td class="line_item-total">$0.00</td>
      <td class="line_item-remove">
        <%= hidden_field_tag 'order[line_items_attributes][-##-][_destroy]' %>
        <a href="#" class="btn btn-xs btn-danger line_item-remove_btn">
          <span class="glyphicon glyphicon-remove"></span>
        </a>
      </td>
    </tr>
  </table>
<% end %>

app/views/orders/edit.html.erb
<%= render 'header' %>

<div class="row">
  <div class="col-md-2">
    <p>
      <%= link_to @order, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-arrow-left"></span>
        Cancel
      <% end %>
    </p>
  </div>
  <div class="col-md-10">
    <%= render 'form' %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="page-header">
  <h1>
    Orders
    <small><%= @site.name if @site %></small>
  </h1>
</div>

<%= new_order_button %>

<hr>

<ul class="nav nav-tabs">
  <%= active_li(action: 'index') do %>
    <%= link_to 'All', orders_path %>
  <% end %>
  <%= active_li(action: 'draft') do %>
    <%= link_to 'Drafts', draft_orders_path %>
  <% end %>
  <%= active_li(action: 'submitted') do %>
    <%= link_to 'Submitted', submitted_orders_path %>
  <% end %>
  <%= active_li(action: 'approved') do %>
    <%= link_to 'Approved', approved_orders_path %>
  <% end %>
  <%= active_li(action: 'fulfilled') do %>
    <%= link_to 'Fulfilled', fulfilled_orders_path %>
  <% end %>
  <%= active_li(action: 'archived') do %>
    <%= link_to 'Archived', archived_orders_path %>
  <% end %>
</ul>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Order #</th>
      <th>Site</th>
      <th>Started by</th>
      <th>State</th>
      <th>Total</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr class="order-row" href="<%= order_path(order) %>">
        <td>
          <%= order.id %>
        </td>
        <td><%= order.site.name if order.site %></td>
        <td><%= order.user.name %></td>
        <td><%= order.state %></td>
        <td><%= number_to_currency order.total %></td>        
        <td>
          <%= link_to 'View', order, class: 'btn btn-default' %>
          <% if order.editable_by?(current_user) %>
            <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-default' %>
            <%# next_step_link_for( order ) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @draft_order %>
<div class="modal fade" id="new_order_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Do you need to start a new order?</h4>
      </div>
      <div class="modal-body">
        An open order already exists. Are you sure you really need a new one?
      </div>
      <div class="modal-footer">
        <%= link_to 'Start a new order', new_order_path, class: 'btn btn-default' %>
        <%= link_to 'Continue with open order', order_path(@draft_order), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/orders/new.html.erb
<header>
  <div class="row">
    <div class="col-sm-12">
      <p>
        <%= link_to @order, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-arrow-left"></span>
          Cancel
        <% end %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1>New order</h1>
    </div>
  </div>
</header>

<%= render 'form' %>

app/views/orders/show.html.erb
<%= render 'header' %>

<% present @order do |presenter| %>

<div class="row">
  <div class="col-md-9">

    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">
          Line Items
        </div>
      </div>
      <div class="panel-body">
        <%= render @order %>
      </div>
    </div>

  </div>
  <div class="col-md-3">

    <% if @order.editable_by?(current_user) %>
      <%= link_to 'Edit this order', edit_order_path(@order), class: 'btn btn-primary'  %>
    <% end %>
    <hr>

    <section class="workflow_control">
      <h4 class="workflow_control-title">Next Step</h4>
      <%= presenter.workflow_button %>
    </section>

  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <%= render 'comments' %>
  </div>
</div>

<% end %>