config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :state_scopeable do
    collection do
      get :draft
      get :submitted
      get :approved
      get :fulfilled
      get :archived
    end
  end

  resources :sites, only: [:index] do
    resources :orders, only: [:index], concerns: :state_scopeable
  end

  resources :orders, concerns: :state_scopeable do
    member do
      put :review
      put :submit
      put :approve
      put :fulfill
      put :archive
      put :cancel
    end

    resources :line_items
    resources :comments, only: [:create]
    resources :approvals, only: [:create]
  end

  resources :products
  resources :product_groups
  resources :imports, only: [:new, :create]

  namespace :admin do
    resources :sites
    resources :users
    resources :roles
  end

  authenticated :user, lambda {|u| u.staff?} do
    root to: 'orders#draft', as: :staff_root
  end

  authenticated :user, lambda {|u| u.approver?} do
    root to: 'orders#submitted', as: :approver_root
  end

  authenticated :user, lambda {|u| u.warehouse?} do
    root to: 'orders#approved', as: :warehouse_root
  end

  authenticated :user, lambda {|u| u.finance?} do
    root to: 'orders#fulfilled', as: :finance_root
  end

  root to: 'orders#index'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  item_id          :string
#  description      :string
#  measure          :string
#  cost_cents       :integer          default("0"), not null
#  state            :integer          default("0")
#  created_at       :datetime
#  updated_at       :datetime
#  product_group_id :integer
#

class Product < ActiveRecord::Base
  include AASM
  
  monetize :cost_cents
  
  enum state: {enabled: 0, disabled: 1}
  
  validates_uniqueness_of :item_id
  
  belongs_to :product_group
  has_many :line_items
  has_many :orders, through: :line_items
  
  before_destroy :check_for_line_items
  
  def search_str
    "#{item_id} #{description}".gsub(/\"/,'')
  end
  
  def check_for_line_items
    if line_items.any?
      errors.add(:base, "Orders exist with this product, hide it instead.")
      return false
    else
      return true
    end
  end
  
  def deletable?
    line_items.none?
  end
  
  aasm column: :state, enum: true do
    state :enabled
    state :disabled
    
    event :disable do
      transitions from: :enabled, to: :disabled
    end
    
    event :enable do
      transitions from: :disabled, to: :enabled
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :authorize_for_inventory

  # GET /products
  # GET /products.json
  def index
    @product_groups = ProductGroup.order(:group_number).includes(:active_products)
    @disabled = Product.disabled
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @line_items = @product.line_items.order(created_at: :desc)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:item_id, :description, :measure, :cost, :state)
    end
    
    def authorize_for_inventory
      authorize! { signed_in? }
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_row_tag(product)
    options = {
      data: {
        item_id: product.item_id,
        search: product.search_str,
        cost: product.cost_cents
      },
      class: 'product-row'
    }
    
    content_tag_for(:tr, product, nil, options) do
      yield if block_given?
    end
  end
end

app/views/products/_form.html.erb
<%= bootstrap_form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.text_field :item_id %>
  <%= f.text_field :description %>
  <%= f.text_field :measure %>
  <%= f.text_field :cost %>
  
  <div class="form-group">
    <label for="product_state" class="control-label">State</label><br>
    <%= f.radio_button :state, 'enabled', label: "Enabled", checked: @product.enabled?, inline: true %>
    <%= f.radio_button :state, 'disabled', label: "Disabled", checked: @product.disabled?, inline: true %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Update Product', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= content_tag_for :article, product do %>
  <div class="row">
    <div class="col-md-8">
      <div class="product-item_id">
        <%= product.item_id %>
      </div>
      <div class="product-desc">
        <%= product.description %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="product-cost">
        <%= product.cost %> per <%= product.measure %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/_product_form.html.erb
<tr>
  <td>
    <%= product.description %><br>
    <small><%= product.item_id %></small>
  </td>
  <td><%= product.measure %></td>
  <td><%= product.cost %></td>
  <td>
    <div class="form-group">
      <%= label_tag :quantity, nil, class: 'sr-only' %>
      <%= text_field_tag :quantity, nil, placeholder: 'qty', size: 2, id: nil, class: 'line_item_quantity' %>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= hidden_field_tag :product_id, product.id %>
      <%= link_to 'Add to order', '#', class: 'btn btn-xs btn-default' %>
    </div>
  </td>
</tr>

app/views/products/_product_row.html.erb
<%= product_row_tag product do %>
  <td class="product-item_id"><%= product.item_id %></td>
  <td class="product-desc"><%= product.description %></td>
  <td class="product-measure"><%= product.measure %></td>
  <td class="product-cost"><%= number_to_currency product.cost %></td>
  <td class="product-op product-view">
    <%= link_to 'View', product_path(product), class: 'btn btn-default' %>
  </td>
  <td class="product-op product-edit">
    <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-default' %>
  </td>
  <td class="product-op product-add">
    <%= link_to 'Add to order', 'javascript:;', class: 'btn btn-default' %>
  </td>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <h1>Editing product</h1>
</div>

<div class="row">
  <div class="col-md-2">
    <%= link_to products_path, class: 'btn btn-block btn-default' do %>
      <span class="glyphicon glyphicon-arrow-left"></span>
      All Products
    <% end %>
    <hr>
    <% if @product.deletable? %>
      <%= link_to 'Delete', product_path(@product), method: :delete, class: 'btn btn-block btn-danger', data: {confirm: "Are you sure?"} %>
    <% else %>
      This product is referenced in orders and cannot be deleted.
      You can disable it to keep it from being ordered from now on.
    <% end %>
  </div>
  
  <div class="col-md-10">
    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<div class="page-header">
  <h1>Inventory</h1>
  
  <% if current_user.admin? %>
  <ul class="nav nav-pills">
    <%= active_li(controller: 'imports', action: 'new') do %>
      <%= link_to 'New Product', new_product_path %>
    <% end %>
    <%= active_li(controller: 'imports') do %>
      <%= link_to 'Import', new_import_path %>
    <% end %>
  </ul>
  <% end %>
  
</div>

<div id="inventory">
  <%= render @product_groups %>
</div>

<div id="disabled_products" class="panel panel-danger">
  <div class="panel-heading">
    <div class="panel-title">
      Disabled Products
    </div>
  </div>
  
  <table class="products-table table table-striped">
    <thead>
      <tr>
        <th>Item</th>
        <th>Description</th>
        <th>UOM</th>
        <th>Cost</th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: 'products/product_row', collection: @disabled, as: 'product' %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    All Products
  <% end %>
</p>


<div class="page-header">
  <h1>
    <%= @product.item_id %>
    <small><%= @product.description %></small>
  </h1>
</div>

<p>
  <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %>
</p>

<p>
  <strong>Unit of Measure:</strong>
  <%= @product.measure %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>




<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h4>Orders<h4>
    </div>
  </div>
  
  <table class="table table-striped">
    <tr>
      <th>Qty</th>
      <th>Order</th>
    </tr>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.quantity %></td>
        <td><%= link_to "Order ##{line_item.order_id}", order_path(line_item.order_id) %></td>
      </tr>
    <% end %>
  </table>
</div>