config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :state_scopeable do
    collection do
      get :draft
      get :submitted
      get :approved
      get :fulfilled
      get :archived
    end
  end

  resources :sites, only: [:index] do
    resources :orders, only: [:index], concerns: :state_scopeable
  end

  resources :orders, concerns: :state_scopeable do
    member do
      put :review
      put :submit
      put :approve
      put :fulfill
      put :archive
      put :cancel
    end

    resources :line_items
    resources :comments, only: [:create]
    resources :approvals, only: [:create]
  end

  resources :products
  resources :product_groups
  resources :imports, only: [:new, :create]

  namespace :admin do
    resources :sites
    resources :users
    resources :roles
  end

  authenticated :user, lambda {|u| u.staff?} do
    root to: 'orders#draft', as: :staff_root
  end

  authenticated :user, lambda {|u| u.approver?} do
    root to: 'orders#submitted', as: :approver_root
  end

  authenticated :user, lambda {|u| u.warehouse?} do
    root to: 'orders#approved', as: :warehouse_root
  end

  authenticated :user, lambda {|u| u.finance?} do
    root to: 'orders#fulfilled', as: :finance_root
  end

  root to: 'orders#index'

end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id         :integer          not null, primary key
#  name       :string
#  code       :integer
#  abbr       :string
#  created_at :datetime
#  updated_at :datetime
#

class Site < ActiveRecord::Base
  has_many :orders
  has_many :users
  
  def self.by_param(param)
    if param.to_i > 0
      find(param)
    else
      find_by(abbr: param)
    end
  end
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < AdminController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  after_action :authorize_admin

  # GET /sites
  # GET /sites.json
  def index
    @sites = sites_scope
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to [:admin, @site], notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to [:admin, @site], notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to admin_sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_site
    @site = Site.find(params[:id])
  end
  
  def sites_scope
    Site.order(:code)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def site_params
    params.require(:site).permit(:name, :code, :abbr)
  end
  
  def authorize_admin
    authorize!{ current_user.admin? }
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.order(:abbr)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :abbr %><br>
    <%= f.text_field :abbr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/index.html.erb
<header class="page-header">
  <h1>Sites</h1>
</header>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      
      <ul>
        <% @sites.each do |site| %>
          <li><%= link_to site.name, site_orders_path(site) %></li>
        <% end %>
      </ul>
      
    </div>
  </div>
</div>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @site.code %>
</p>

<p>
  <strong>Abbr:</strong>
  <%= @site.abbr %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>