config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  concern :state_scopeable do
    collection do
      get :draft
      get :submitted
      get :approved
      get :fulfilled
      get :archived
    end
  end

  resources :sites, only: [:index] do
    resources :orders, only: [:index], concerns: :state_scopeable
  end

  resources :orders, concerns: :state_scopeable do
    member do
      put :review
      put :submit
      put :approve
      put :fulfill
      put :archive
      put :cancel
    end

    resources :line_items
    resources :comments, only: [:create]
    resources :approvals, only: [:create]
  end

  resources :products
  resources :product_groups
  resources :imports, only: [:new, :create]

  namespace :admin do
    resources :sites
    resources :users
    resources :roles
  end

  authenticated :user, lambda {|u| u.staff?} do
    root to: 'orders#draft', as: :staff_root
  end

  authenticated :user, lambda {|u| u.approver?} do
    root to: 'orders#submitted', as: :approver_root
  end

  authenticated :user, lambda {|u| u.warehouse?} do
    root to: 'orders#approved', as: :warehouse_root
  end

  authenticated :user, lambda {|u| u.finance?} do
    root to: 'orders#fulfilled', as: :finance_root
  end

  root to: 'orders#index'

end

app/views/layouts/_flash.html.erb
<% if flash && flash.any? %>
<section class="flash">
  <% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
  <% end %>
</section>
<% end %>

<% if current_user && user_not_configured? %>
<section class="flash">
  <div class="alert alert-warning">
    Your account isn't setup yet. Ask IT for help.
  </div>
</section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUSD Warehouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimal-ui">
  <meta name="apple-mobile-web-app-capable" content="yes">
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SUSD Warehouse</a>
    </div>

    <% if signed_in? %>
    <div class="collapse navbar-collapse" id="main-navbar-collapse">

      <ul class="nav navbar-nav">
        <% if current_user.manages_products? %>
          <%= active_li(controller: 'products') do %>
            <%= link_to 'Inventory', products_path %>
          <% end %>
        <% end %>
        <%= active_li(controller: 'orders') do %>
          <%= link_to 'Orders', orders_path %>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user.admin? %>
        <li class="dropdown">
          <%= link_to admin_sites_path, {class: 'dropdown-toggle', data:{toggle: 'dropdown'} } do %>
            Admin <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Sites', admin_sites_path %></li>
            <li><%= link_to 'Users', admin_users_path %></li>
            <li><%= link_to 'Roles', admin_roles_path %></li>
          </ul>
        </li>
        <% end %>
        <li class="navbar-text">
          Signed in as <%= current_user.name %>
          <% if current_user.google_image_url.present? %>
            <%= image_tag current_user.google_image_url, class: 'avatar-sm' %>
          <% end %>
        </li>
        <li><%= link_to 'Sign-out', destroy_user_session_path, method: :delete %></li>
      </ul>

    </div>
    <% end %>

  </div>
</nav>

<div class="container">
  <%= render 'layouts/flash' %>
  <%= yield %>
</div>


</body>
</html>